/*
 * Qase.io TestOps API v2
 *
 * Qase TestOps API v2 Specification.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Qase.ApiClient.V2.Api;
using Qase.ApiClient.V2.Model;

namespace Qase.ApiClient.V2.Client
{
    /// <summary>
    /// Provides hosting configuration for Qase.ApiClient.V2
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new BaseResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateResultsRequestV2JsonConverter());
            _jsonOptions.Converters.Add(new CustomFieldJsonConverter());
            _jsonOptions.Converters.Add(new CustomFieldListResponseJsonConverter());
            _jsonOptions.Converters.Add(new CustomFieldListResponseAllOfResultJsonConverter());
            _jsonOptions.Converters.Add(new CustomFieldOptionJsonConverter());
            _jsonOptions.Converters.Add(new CustomFieldResponseJsonConverter());
            _jsonOptions.Converters.Add(new RelationSuiteJsonConverter());
            _jsonOptions.Converters.Add(new RelationSuiteItemJsonConverter());
            _jsonOptions.Converters.Add(new ResultCreateJsonConverter());
            _jsonOptions.Converters.Add(new ResultCreateBulkResponseJsonConverter());
            _jsonOptions.Converters.Add(new ResultCreateFieldsJsonConverter());
            _jsonOptions.Converters.Add(new ResultCreateResponseJsonConverter());
            _jsonOptions.Converters.Add(new ResultCreateResponseAllOfResultJsonConverter());
            _jsonOptions.Converters.Add(new ResultExecutionJsonConverter());
            _jsonOptions.Converters.Add(new ResultRelationsJsonConverter());
            _jsonOptions.Converters.Add(new ResultStepJsonConverter());
            _jsonOptions.Converters.Add(new ResultStepDataJsonConverter());
            _jsonOptions.Converters.Add(new ResultStepExecutionJsonConverter());
            _jsonOptions.Converters.Add(new ResultStepStatusJsonConverter());
            _jsonOptions.Converters.Add(new ResultStepStatusNullableJsonConverter());
            _jsonOptions.Converters.Add(new ResultStepsTypeJsonConverter());
            _jsonOptions.Converters.Add(new ResultStepsTypeNullableJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new JsonSerializerOptionsProvider(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<CustomFieldsApiEvents>();
            _services.AddSingleton<ResultsApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<ICustomFieldsApi, CustomFieldsApi>(client));
            builders.Add(_services.AddHttpClient<IResultsApi, ResultsApi>(client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
