// <auto-generated>
/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Qase.ApiClient.V1.Client;

namespace Qase.ApiClient.V1.Model
{
    /// <summary>
    /// CustomFieldCreate
    /// </summary>
    public partial class CustomFieldCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomFieldCreate" /> class.
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="entity">Possible values: 0 - case; 1 - run; 2 - defect; </param>
        /// <param name="type">Possible values: 0 - number; 1 - string; 2 - text; 3 - selectbox; 4 - checkbox; 5 - radio; 6 - multiselect; 7 - url; 8 - user; 9 - datetime; </param>
        /// <param name="value">Required if type one of: 3 - selectbox; 5 - radio; 6 - multiselect; </param>
        /// <param name="placeholder">placeholder</param>
        /// <param name="defaultValue">defaultValue</param>
        /// <param name="isFilterable">isFilterable</param>
        /// <param name="isVisible">isVisible</param>
        /// <param name="isRequired">isRequired</param>
        /// <param name="isEnabledForAllProjects">isEnabledForAllProjects</param>
        /// <param name="projectsCodes">projectsCodes</param>
        [JsonConstructor]
        public CustomFieldCreate(string title, int entity, int type, Option<List<CustomFieldCreateValueInner>?> value = default, Option<string?> placeholder = default, Option<string?> defaultValue = default, Option<bool?> isFilterable = default, Option<bool?> isVisible = default, Option<bool?> isRequired = default, Option<bool?> isEnabledForAllProjects = default, Option<List<string>?> projectsCodes = default)
        {
            Title = title;
            Entity = entity;
            Type = type;
            ValueOption = value;
            PlaceholderOption = placeholder;
            DefaultValueOption = defaultValue;
            IsFilterableOption = isFilterable;
            IsVisibleOption = isVisible;
            IsRequiredOption = isRequired;
            IsEnabledForAllProjectsOption = isEnabledForAllProjects;
            ProjectsCodesOption = projectsCodes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// Possible values: 0 - case; 1 - run; 2 - defect; 
        /// </summary>
        /// <value>Possible values: 0 - case; 1 - run; 2 - defect; </value>
        [JsonPropertyName("entity")]
        public int Entity { get; set; }

        /// <summary>
        /// Possible values: 0 - number; 1 - string; 2 - text; 3 - selectbox; 4 - checkbox; 5 - radio; 6 - multiselect; 7 - url; 8 - user; 9 - datetime; 
        /// </summary>
        /// <value>Possible values: 0 - number; 1 - string; 2 - text; 3 - selectbox; 4 - checkbox; 5 - radio; 6 - multiselect; 7 - url; 8 - user; 9 - datetime; </value>
        [JsonPropertyName("type")]
        public int Type { get; set; }

        /// <summary>
        /// Used to track the state of Value
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CustomFieldCreateValueInner>?> ValueOption { get; private set; }

        /// <summary>
        /// Required if type one of: 3 - selectbox; 5 - radio; 6 - multiselect; 
        /// </summary>
        /// <value>Required if type one of: 3 - selectbox; 5 - radio; 6 - multiselect; </value>
        [JsonPropertyName("value")]
        public List<CustomFieldCreateValueInner>? Value { get { return this.ValueOption; } set { this.ValueOption = new Option<List<CustomFieldCreateValueInner>?>(value); } }

        /// <summary>
        /// Used to track the state of Placeholder
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PlaceholderOption { get; private set; }

        /// <summary>
        /// Gets or Sets Placeholder
        /// </summary>
        [JsonPropertyName("placeholder")]
        public string? Placeholder { get { return this.PlaceholderOption; } set { this.PlaceholderOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of DefaultValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DefaultValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets DefaultValue
        /// </summary>
        [JsonPropertyName("default_value")]
        public string? DefaultValue { get { return this.DefaultValueOption; } set { this.DefaultValueOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of IsFilterable
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsFilterableOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsFilterable
        /// </summary>
        [JsonPropertyName("is_filterable")]
        public bool? IsFilterable { get { return this.IsFilterableOption; } set { this.IsFilterableOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of IsVisible
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsVisibleOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsVisible
        /// </summary>
        [JsonPropertyName("is_visible")]
        public bool? IsVisible { get { return this.IsVisibleOption; } set { this.IsVisibleOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of IsRequired
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsRequiredOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsRequired
        /// </summary>
        [JsonPropertyName("is_required")]
        public bool? IsRequired { get { return this.IsRequiredOption; } set { this.IsRequiredOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of IsEnabledForAllProjects
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsEnabledForAllProjectsOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsEnabledForAllProjects
        /// </summary>
        [JsonPropertyName("is_enabled_for_all_projects")]
        public bool? IsEnabledForAllProjects { get { return this.IsEnabledForAllProjectsOption; } set { this.IsEnabledForAllProjectsOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of ProjectsCodes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ProjectsCodesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProjectsCodes
        /// </summary>
        [JsonPropertyName("projects_codes")]
        public List<string>? ProjectsCodes { get { return this.ProjectsCodesOption; } set { this.ProjectsCodesOption = new Option<List<string>?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomFieldCreate {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Entity: ").Append(Entity).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Placeholder: ").Append(Placeholder).Append("\n");
            sb.Append("  DefaultValue: ").Append(DefaultValue).Append("\n");
            sb.Append("  IsFilterable: ").Append(IsFilterable).Append("\n");
            sb.Append("  IsVisible: ").Append(IsVisible).Append("\n");
            sb.Append("  IsRequired: ").Append(IsRequired).Append("\n");
            sb.Append("  IsEnabledForAllProjects: ").Append(IsEnabledForAllProjects).Append("\n");
            sb.Append("  ProjectsCodes: ").Append(ProjectsCodes).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Title, length must be less than 255.", new [] { "Title" });
            }

            // Entity (int) maximum
            if (this.Entity > (int)2)
            {
                yield return new ValidationResult("Invalid value for Entity, must be a value less than or equal to 2.", new [] { "Entity" });
            }

            // Entity (int) minimum
            if (this.Entity < (int)0)
            {
                yield return new ValidationResult("Invalid value for Entity, must be a value greater than or equal to 0.", new [] { "Entity" });
            }

            // Type (int) maximum
            if (this.Type > (int)9)
            {
                yield return new ValidationResult("Invalid value for Type, must be a value less than or equal to 9.", new [] { "Type" });
            }

            // Type (int) minimum
            if (this.Type < (int)0)
            {
                yield return new ValidationResult("Invalid value for Type, must be a value greater than or equal to 0.", new [] { "Type" });
            }

            // Placeholder (string) maxLength
            if (this.Placeholder != null && this.Placeholder.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Placeholder, length must be less than 255.", new [] { "Placeholder" });
            }

            // DefaultValue (string) maxLength
            if (this.DefaultValue != null && this.DefaultValue.Length > 255)
            {
                yield return new ValidationResult("Invalid value for DefaultValue, length must be less than 255.", new [] { "DefaultValue" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CustomFieldCreate" />
    /// </summary>
    public class CustomFieldCreateJsonConverter : JsonConverter<CustomFieldCreate>
    {
        /// <summary>
        /// Deserializes json to <see cref="CustomFieldCreate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CustomFieldCreate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<int?> entity = default;
            Option<int?> type = default;
            Option<List<CustomFieldCreateValueInner>?> value = default;
            Option<string?> placeholder = default;
            Option<string?> defaultValue = default;
            Option<bool?> isFilterable = default;
            Option<bool?> isVisible = default;
            Option<bool?> isRequired = default;
            Option<bool?> isEnabledForAllProjects = default;
            Option<List<string>?> projectsCodes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "entity":
                            entity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "type":
                            type = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "value":
                            value = new Option<List<CustomFieldCreateValueInner>?>(JsonSerializer.Deserialize<List<CustomFieldCreateValueInner>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "placeholder":
                            placeholder = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "default_value":
                            defaultValue = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "is_filterable":
                            isFilterable = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "is_visible":
                            isVisible = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "is_required":
                            isRequired = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "is_enabled_for_all_projects":
                            isEnabledForAllProjects = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "projects_codes":
                            projectsCodes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class CustomFieldCreate.", nameof(title));

            if (!entity.IsSet)
                throw new ArgumentException("Property is required for class CustomFieldCreate.", nameof(entity));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class CustomFieldCreate.", nameof(type));

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class CustomFieldCreate.");

            if (entity.IsSet && entity.Value == null)
                throw new ArgumentNullException(nameof(entity), "Property is not nullable for class CustomFieldCreate.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class CustomFieldCreate.");

            if (isFilterable.IsSet && isFilterable.Value == null)
                throw new ArgumentNullException(nameof(isFilterable), "Property is not nullable for class CustomFieldCreate.");

            if (isVisible.IsSet && isVisible.Value == null)
                throw new ArgumentNullException(nameof(isVisible), "Property is not nullable for class CustomFieldCreate.");

            if (isRequired.IsSet && isRequired.Value == null)
                throw new ArgumentNullException(nameof(isRequired), "Property is not nullable for class CustomFieldCreate.");

            if (isEnabledForAllProjects.IsSet && isEnabledForAllProjects.Value == null)
                throw new ArgumentNullException(nameof(isEnabledForAllProjects), "Property is not nullable for class CustomFieldCreate.");

            if (projectsCodes.IsSet && projectsCodes.Value == null)
                throw new ArgumentNullException(nameof(projectsCodes), "Property is not nullable for class CustomFieldCreate.");

            return new CustomFieldCreate(title.Value!, entity.Value!.Value!, type.Value!.Value!, value, placeholder, defaultValue, isFilterable, isVisible, isRequired, isEnabledForAllProjects, projectsCodes);
        }

        /// <summary>
        /// Serializes a <see cref="CustomFieldCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customFieldCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CustomFieldCreate customFieldCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, customFieldCreate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CustomFieldCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="customFieldCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CustomFieldCreate customFieldCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (customFieldCreate.Title == null)
                throw new ArgumentNullException(nameof(customFieldCreate.Title), "Property is required for class CustomFieldCreate.");

            if (customFieldCreate.ProjectsCodesOption.IsSet && customFieldCreate.ProjectsCodes == null)
                throw new ArgumentNullException(nameof(customFieldCreate.ProjectsCodes), "Property is required for class CustomFieldCreate.");

            writer.WriteString("title", customFieldCreate.Title);

            writer.WriteNumber("entity", customFieldCreate.Entity);

            writer.WriteNumber("type", customFieldCreate.Type);

            if (customFieldCreate.ValueOption.IsSet)
                if (customFieldCreate.ValueOption.Value != null)
                {
                    writer.WritePropertyName("value");
                    JsonSerializer.Serialize(writer, customFieldCreate.Value, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("value");
            if (customFieldCreate.PlaceholderOption.IsSet)
                if (customFieldCreate.PlaceholderOption.Value != null)
                    writer.WriteString("placeholder", customFieldCreate.Placeholder);
                else
                    writer.WriteNull("placeholder");

            if (customFieldCreate.DefaultValueOption.IsSet)
                if (customFieldCreate.DefaultValueOption.Value != null)
                    writer.WriteString("default_value", customFieldCreate.DefaultValue);
                else
                    writer.WriteNull("default_value");

            if (customFieldCreate.IsFilterableOption.IsSet)
                writer.WriteBoolean("is_filterable", customFieldCreate.IsFilterableOption.Value!.Value);

            if (customFieldCreate.IsVisibleOption.IsSet)
                writer.WriteBoolean("is_visible", customFieldCreate.IsVisibleOption.Value!.Value);

            if (customFieldCreate.IsRequiredOption.IsSet)
                writer.WriteBoolean("is_required", customFieldCreate.IsRequiredOption.Value!.Value);

            if (customFieldCreate.IsEnabledForAllProjectsOption.IsSet)
                writer.WriteBoolean("is_enabled_for_all_projects", customFieldCreate.IsEnabledForAllProjectsOption.Value!.Value);

            if (customFieldCreate.ProjectsCodesOption.IsSet)
            {
                writer.WritePropertyName("projects_codes");
                JsonSerializer.Serialize(writer, customFieldCreate.ProjectsCodes, jsonSerializerOptions);
            }
        }
    }
}
