// <auto-generated>
/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Qase.ApiClient.V1.Client;

namespace Qase.ApiClient.V1.Model
{
    /// <summary>
    /// The test case fields proposed by the review.
    /// </summary>
    public partial class ReviewCaseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReviewCaseData" /> class.
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="description">description</param>
        /// <param name="preconditions">preconditions</param>
        /// <param name="postconditions">postconditions</param>
        /// <param name="severity">severity</param>
        /// <param name="priority">priority</param>
        /// <param name="behavior">behavior</param>
        /// <param name="type">type</param>
        /// <param name="layer">layer</param>
        /// <param name="isFlaky">isFlaky</param>
        /// <param name="isMuted">Mute state of the proposed test case.</param>
        /// <param name="suiteId">suiteId</param>
        /// <param name="milestoneId">milestoneId</param>
        /// <param name="isManual">&#x60;true&#x60; if the case is manual, &#x60;false&#x60; if it is automated.</param>
        /// <param name="isToBeAutomated">&#x60;true&#x60; if a manual case is planned to be automated.</param>
        /// <param name="status">status</param>
        /// <param name="stepsType">Format of the steps field. Omit to keep the current one, &#x60;classic&#x60; for a new-case draft; changing it requires sending &#x60;steps&#x60; in the same request.</param>
        /// <param name="attachments">A list of Attachment hashes.</param>
        /// <param name="steps">For gherkin steps send the scenario in &#x60;value&#x60;.</param>
        /// <param name="tags">tags</param>
        /// <param name="parameters">parameters</param>
        /// <param name="customField">Map of custom field ID to value. A &#x60;create&#x60; review must carry every required custom field. An &#x60;edit&#x60; review is validated against the current test case, so send only the fields the proposal changes.</param>
        [JsonConstructor]
        public ReviewCaseData(Option<string?> title = default, Option<string?> description = default, Option<string?> preconditions = default, Option<string?> postconditions = default, Option<int?> severity = default, Option<int?> priority = default, Option<int?> behavior = default, Option<int?> type = default, Option<int?> layer = default, Option<int?> isFlaky = default, Option<bool?> isMuted = default, Option<long?> suiteId = default, Option<long?> milestoneId = default, Option<bool?> isManual = default, Option<bool?> isToBeAutomated = default, Option<int?> status = default, Option<StepsTypeEnum?> stepsType = default, Option<List<string>?> attachments = default, Option<List<ReviewStepData>?> steps = default, Option<List<string>?> tags = default, Option<List<TestCaseParameterCreate>?> parameters = default, Option<Dictionary<string, string>?> customField = default)
        {
            TitleOption = title;
            DescriptionOption = description;
            PreconditionsOption = preconditions;
            PostconditionsOption = postconditions;
            SeverityOption = severity;
            PriorityOption = priority;
            BehaviorOption = behavior;
            TypeOption = type;
            LayerOption = layer;
            IsFlakyOption = isFlaky;
            IsMutedOption = isMuted;
            SuiteIdOption = suiteId;
            MilestoneIdOption = milestoneId;
            IsManualOption = isManual;
            IsToBeAutomatedOption = isToBeAutomated;
            StatusOption = status;
            StepsTypeOption = stepsType;
            AttachmentsOption = attachments;
            StepsOption = steps;
            TagsOption = tags;
            ParametersOption = parameters;
            CustomFieldOption = customField;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Format of the steps field. Omit to keep the current one, &#x60;classic&#x60; for a new-case draft; changing it requires sending &#x60;steps&#x60; in the same request.
        /// </summary>
        /// <value>Format of the steps field. Omit to keep the current one, &#x60;classic&#x60; for a new-case draft; changing it requires sending &#x60;steps&#x60; in the same request.</value>
        public enum StepsTypeEnum
        {
            /// <summary>
            /// Enum Classic for value: classic
            /// </summary>
            Classic = 1,

            /// <summary>
            /// Enum Gherkin for value: gherkin
            /// </summary>
            Gherkin = 2
        }

        /// <summary>
        /// Returns a <see cref="StepsTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StepsTypeEnum StepsTypeEnumFromString(string value)
        {
            if (value.Equals("classic"))
                return StepsTypeEnum.Classic;

            if (value.Equals("gherkin"))
                return StepsTypeEnum.Gherkin;

            throw new NotImplementedException($"Could not convert value to type StepsTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StepsTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StepsTypeEnum? StepsTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("classic"))
                return StepsTypeEnum.Classic;

            if (value.Equals("gherkin"))
                return StepsTypeEnum.Gherkin;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StepsTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StepsTypeEnumToJsonValue(StepsTypeEnum? value)
        {
            if (value == StepsTypeEnum.Classic)
                return "classic";

            if (value == StepsTypeEnum.Gherkin)
                return "gherkin";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of StepsType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StepsTypeEnum?> StepsTypeOption { get; private set; }

        /// <summary>
        /// Format of the steps field. Omit to keep the current one, &#x60;classic&#x60; for a new-case draft; changing it requires sending &#x60;steps&#x60; in the same request.
        /// </summary>
        /// <value>Format of the steps field. Omit to keep the current one, &#x60;classic&#x60; for a new-case draft; changing it requires sending &#x60;steps&#x60; in the same request.</value>
        [JsonPropertyName("steps_type")]
        public StepsTypeEnum? StepsType { get { return this.StepsTypeOption; } set { this.StepsTypeOption = new Option<StepsTypeEnum?>(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Preconditions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PreconditionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Preconditions
        /// </summary>
        [JsonPropertyName("preconditions")]
        public string? Preconditions { get { return this.PreconditionsOption; } set { this.PreconditionsOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Postconditions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PostconditionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Postconditions
        /// </summary>
        [JsonPropertyName("postconditions")]
        public string? Postconditions { get { return this.PostconditionsOption; } set { this.PostconditionsOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Severity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SeverityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Severity
        /// </summary>
        [JsonPropertyName("severity")]
        public int? Severity { get { return this.SeverityOption; } set { this.SeverityOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Priority
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PriorityOption { get; private set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [JsonPropertyName("priority")]
        public int? Priority { get { return this.PriorityOption; } set { this.PriorityOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Behavior
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> BehaviorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Behavior
        /// </summary>
        [JsonPropertyName("behavior")]
        public int? Behavior { get { return this.BehaviorOption; } set { this.BehaviorOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public int? Type { get { return this.TypeOption; } set { this.TypeOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Layer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LayerOption { get; private set; }

        /// <summary>
        /// Gets or Sets Layer
        /// </summary>
        [JsonPropertyName("layer")]
        public int? Layer { get { return this.LayerOption; } set { this.LayerOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of IsFlaky
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IsFlakyOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsFlaky
        /// </summary>
        [JsonPropertyName("is_flaky")]
        public int? IsFlaky { get { return this.IsFlakyOption; } set { this.IsFlakyOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of IsMuted
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsMutedOption { get; private set; }

        /// <summary>
        /// Mute state of the proposed test case.
        /// </summary>
        /// <value>Mute state of the proposed test case.</value>
        [JsonPropertyName("is_muted")]
        public bool? IsMuted { get { return this.IsMutedOption; } set { this.IsMutedOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of SuiteId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SuiteIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SuiteId
        /// </summary>
        [JsonPropertyName("suite_id")]
        public long? SuiteId { get { return this.SuiteIdOption; } set { this.SuiteIdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of MilestoneId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> MilestoneIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets MilestoneId
        /// </summary>
        [JsonPropertyName("milestone_id")]
        public long? MilestoneId { get { return this.MilestoneIdOption; } set { this.MilestoneIdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of IsManual
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsManualOption { get; private set; }

        /// <summary>
        /// &#x60;true&#x60; if the case is manual, &#x60;false&#x60; if it is automated.
        /// </summary>
        /// <value>&#x60;true&#x60; if the case is manual, &#x60;false&#x60; if it is automated.</value>
        [JsonPropertyName("is_manual")]
        public bool? IsManual { get { return this.IsManualOption; } set { this.IsManualOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of IsToBeAutomated
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsToBeAutomatedOption { get; private set; }

        /// <summary>
        /// &#x60;true&#x60; if a manual case is planned to be automated.
        /// </summary>
        /// <value>&#x60;true&#x60; if a manual case is planned to be automated.</value>
        [JsonPropertyName("is_to_be_automated")]
        public bool? IsToBeAutomated { get { return this.IsToBeAutomatedOption; } set { this.IsToBeAutomatedOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public int? Status { get { return this.StatusOption; } set { this.StatusOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Attachments
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> AttachmentsOption { get; private set; }

        /// <summary>
        /// A list of Attachment hashes.
        /// </summary>
        /// <value>A list of Attachment hashes.</value>
        [JsonPropertyName("attachments")]
        public List<string>? Attachments { get { return this.AttachmentsOption; } set { this.AttachmentsOption = new Option<List<string>?>(value); } }

        /// <summary>
        /// Used to track the state of Steps
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ReviewStepData>?> StepsOption { get; private set; }

        /// <summary>
        /// For gherkin steps send the scenario in &#x60;value&#x60;.
        /// </summary>
        /// <value>For gherkin steps send the scenario in &#x60;value&#x60;.</value>
        [JsonPropertyName("steps")]
        public List<ReviewStepData>? Steps { get { return this.StepsOption; } set { this.StepsOption = new Option<List<ReviewStepData>?>(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<string>? Tags { get { return this.TagsOption; } set { this.TagsOption = new Option<List<string>?>(value); } }

        /// <summary>
        /// Used to track the state of Parameters
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<TestCaseParameterCreate>?> ParametersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Parameters
        /// </summary>
        [JsonPropertyName("parameters")]
        public List<TestCaseParameterCreate>? Parameters { get { return this.ParametersOption; } set { this.ParametersOption = new Option<List<TestCaseParameterCreate>?>(value); } }

        /// <summary>
        /// Used to track the state of CustomField
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> CustomFieldOption { get; private set; }

        /// <summary>
        /// Map of custom field ID to value. A &#x60;create&#x60; review must carry every required custom field. An &#x60;edit&#x60; review is validated against the current test case, so send only the fields the proposal changes.
        /// </summary>
        /// <value>Map of custom field ID to value. A &#x60;create&#x60; review must carry every required custom field. An &#x60;edit&#x60; review is validated against the current test case, so send only the fields the proposal changes.</value>
        [JsonPropertyName("custom_field")]
        public Dictionary<string, string>? CustomField { get { return this.CustomFieldOption; } set { this.CustomFieldOption = new Option<Dictionary<string, string>?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReviewCaseData {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Preconditions: ").Append(Preconditions).Append("\n");
            sb.Append("  Postconditions: ").Append(Postconditions).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Behavior: ").Append(Behavior).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Layer: ").Append(Layer).Append("\n");
            sb.Append("  IsFlaky: ").Append(IsFlaky).Append("\n");
            sb.Append("  IsMuted: ").Append(IsMuted).Append("\n");
            sb.Append("  SuiteId: ").Append(SuiteId).Append("\n");
            sb.Append("  MilestoneId: ").Append(MilestoneId).Append("\n");
            sb.Append("  IsManual: ").Append(IsManual).Append("\n");
            sb.Append("  IsToBeAutomated: ").Append(IsToBeAutomated).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StepsType: ").Append(StepsType).Append("\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("  Steps: ").Append(Steps).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  CustomField: ").Append(CustomField).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Title, length must be less than 255.", new [] { "Title" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ReviewCaseData" />
    /// </summary>
    public class ReviewCaseDataJsonConverter : JsonConverter<ReviewCaseData>
    {
        /// <summary>
        /// Deserializes json to <see cref="ReviewCaseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ReviewCaseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<string?> description = default;
            Option<string?> preconditions = default;
            Option<string?> postconditions = default;
            Option<int?> severity = default;
            Option<int?> priority = default;
            Option<int?> behavior = default;
            Option<int?> type = default;
            Option<int?> layer = default;
            Option<int?> isFlaky = default;
            Option<bool?> isMuted = default;
            Option<long?> suiteId = default;
            Option<long?> milestoneId = default;
            Option<bool?> isManual = default;
            Option<bool?> isToBeAutomated = default;
            Option<int?> status = default;
            Option<ReviewCaseData.StepsTypeEnum?> stepsType = default;
            Option<List<string>?> attachments = default;
            Option<List<ReviewStepData>?> steps = default;
            Option<List<string>?> tags = default;
            Option<List<TestCaseParameterCreate>?> parameters = default;
            Option<Dictionary<string, string>?> customField = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "preconditions":
                            preconditions = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "postconditions":
                            postconditions = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "severity":
                            severity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "priority":
                            priority = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "behavior":
                            behavior = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "type":
                            type = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "layer":
                            layer = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "is_flaky":
                            isFlaky = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "is_muted":
                            isMuted = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "suite_id":
                            suiteId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "milestone_id":
                            milestoneId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "is_manual":
                            isManual = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "is_to_be_automated":
                            isToBeAutomated = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "status":
                            status = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "steps_type":
                            string? stepsTypeRawValue = utf8JsonReader.GetString();
                            if (stepsTypeRawValue != null)
                                stepsType = new Option<ReviewCaseData.StepsTypeEnum?>(ReviewCaseData.StepsTypeEnumFromStringOrDefault(stepsTypeRawValue));
                            break;
                        case "attachments":
                            attachments = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "steps":
                            steps = new Option<List<ReviewStepData>?>(JsonSerializer.Deserialize<List<ReviewStepData>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tags":
                            tags = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "parameters":
                            parameters = new Option<List<TestCaseParameterCreate>?>(JsonSerializer.Deserialize<List<TestCaseParameterCreate>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "custom_field":
                            customField = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class ReviewCaseData.");

            if (isMuted.IsSet && isMuted.Value == null)
                throw new ArgumentNullException(nameof(isMuted), "Property is not nullable for class ReviewCaseData.");

            if (isManual.IsSet && isManual.Value == null)
                throw new ArgumentNullException(nameof(isManual), "Property is not nullable for class ReviewCaseData.");

            if (isToBeAutomated.IsSet && isToBeAutomated.Value == null)
                throw new ArgumentNullException(nameof(isToBeAutomated), "Property is not nullable for class ReviewCaseData.");

            if (stepsType.IsSet && stepsType.Value == null)
                throw new ArgumentNullException(nameof(stepsType), "Property is not nullable for class ReviewCaseData.");

            if (attachments.IsSet && attachments.Value == null)
                throw new ArgumentNullException(nameof(attachments), "Property is not nullable for class ReviewCaseData.");

            if (steps.IsSet && steps.Value == null)
                throw new ArgumentNullException(nameof(steps), "Property is not nullable for class ReviewCaseData.");

            if (customField.IsSet && customField.Value == null)
                throw new ArgumentNullException(nameof(customField), "Property is not nullable for class ReviewCaseData.");

            return new ReviewCaseData(title, description, preconditions, postconditions, severity, priority, behavior, type, layer, isFlaky, isMuted, suiteId, milestoneId, isManual, isToBeAutomated, status, stepsType, attachments, steps, tags, parameters, customField);
        }

        /// <summary>
        /// Serializes a <see cref="ReviewCaseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="reviewCaseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ReviewCaseData reviewCaseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, reviewCaseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ReviewCaseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="reviewCaseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ReviewCaseData reviewCaseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (reviewCaseData.TitleOption.IsSet && reviewCaseData.Title == null)
                throw new ArgumentNullException(nameof(reviewCaseData.Title), "Property is required for class ReviewCaseData.");

            if (reviewCaseData.AttachmentsOption.IsSet && reviewCaseData.Attachments == null)
                throw new ArgumentNullException(nameof(reviewCaseData.Attachments), "Property is required for class ReviewCaseData.");

            if (reviewCaseData.StepsOption.IsSet && reviewCaseData.Steps == null)
                throw new ArgumentNullException(nameof(reviewCaseData.Steps), "Property is required for class ReviewCaseData.");

            if (reviewCaseData.CustomFieldOption.IsSet && reviewCaseData.CustomField == null)
                throw new ArgumentNullException(nameof(reviewCaseData.CustomField), "Property is required for class ReviewCaseData.");

            if (reviewCaseData.TitleOption.IsSet)
                writer.WriteString("title", reviewCaseData.Title);

            if (reviewCaseData.DescriptionOption.IsSet)
                if (reviewCaseData.DescriptionOption.Value != null)
                    writer.WriteString("description", reviewCaseData.Description);
                else
                    writer.WriteNull("description");

            if (reviewCaseData.PreconditionsOption.IsSet)
                if (reviewCaseData.PreconditionsOption.Value != null)
                    writer.WriteString("preconditions", reviewCaseData.Preconditions);
                else
                    writer.WriteNull("preconditions");

            if (reviewCaseData.PostconditionsOption.IsSet)
                if (reviewCaseData.PostconditionsOption.Value != null)
                    writer.WriteString("postconditions", reviewCaseData.Postconditions);
                else
                    writer.WriteNull("postconditions");

            if (reviewCaseData.SeverityOption.IsSet)
                if (reviewCaseData.SeverityOption.Value != null)
                    writer.WriteNumber("severity", reviewCaseData.SeverityOption.Value!.Value);
                else
                    writer.WriteNull("severity");

            if (reviewCaseData.PriorityOption.IsSet)
                if (reviewCaseData.PriorityOption.Value != null)
                    writer.WriteNumber("priority", reviewCaseData.PriorityOption.Value!.Value);
                else
                    writer.WriteNull("priority");

            if (reviewCaseData.BehaviorOption.IsSet)
                if (reviewCaseData.BehaviorOption.Value != null)
                    writer.WriteNumber("behavior", reviewCaseData.BehaviorOption.Value!.Value);
                else
                    writer.WriteNull("behavior");

            if (reviewCaseData.TypeOption.IsSet)
                if (reviewCaseData.TypeOption.Value != null)
                    writer.WriteNumber("type", reviewCaseData.TypeOption.Value!.Value);
                else
                    writer.WriteNull("type");

            if (reviewCaseData.LayerOption.IsSet)
                if (reviewCaseData.LayerOption.Value != null)
                    writer.WriteNumber("layer", reviewCaseData.LayerOption.Value!.Value);
                else
                    writer.WriteNull("layer");

            if (reviewCaseData.IsFlakyOption.IsSet)
                if (reviewCaseData.IsFlakyOption.Value != null)
                    writer.WriteNumber("is_flaky", reviewCaseData.IsFlakyOption.Value!.Value);
                else
                    writer.WriteNull("is_flaky");

            if (reviewCaseData.IsMutedOption.IsSet)
                writer.WriteBoolean("is_muted", reviewCaseData.IsMutedOption.Value!.Value);

            if (reviewCaseData.SuiteIdOption.IsSet)
                if (reviewCaseData.SuiteIdOption.Value != null)
                    writer.WriteNumber("suite_id", reviewCaseData.SuiteIdOption.Value!.Value);
                else
                    writer.WriteNull("suite_id");

            if (reviewCaseData.MilestoneIdOption.IsSet)
                if (reviewCaseData.MilestoneIdOption.Value != null)
                    writer.WriteNumber("milestone_id", reviewCaseData.MilestoneIdOption.Value!.Value);
                else
                    writer.WriteNull("milestone_id");

            if (reviewCaseData.IsManualOption.IsSet)
                writer.WriteBoolean("is_manual", reviewCaseData.IsManualOption.Value!.Value);

            if (reviewCaseData.IsToBeAutomatedOption.IsSet)
                writer.WriteBoolean("is_to_be_automated", reviewCaseData.IsToBeAutomatedOption.Value!.Value);

            if (reviewCaseData.StatusOption.IsSet)
                if (reviewCaseData.StatusOption.Value != null)
                    writer.WriteNumber("status", reviewCaseData.StatusOption.Value!.Value);
                else
                    writer.WriteNull("status");

            var stepsTypeRawValue = ReviewCaseData.StepsTypeEnumToJsonValue(reviewCaseData.StepsTypeOption.Value!.Value);
            writer.WriteString("steps_type", stepsTypeRawValue);
            if (reviewCaseData.AttachmentsOption.IsSet)
            {
                writer.WritePropertyName("attachments");
                JsonSerializer.Serialize(writer, reviewCaseData.Attachments, jsonSerializerOptions);
            }
            if (reviewCaseData.StepsOption.IsSet)
            {
                writer.WritePropertyName("steps");
                JsonSerializer.Serialize(writer, reviewCaseData.Steps, jsonSerializerOptions);
            }
            if (reviewCaseData.TagsOption.IsSet)
                if (reviewCaseData.TagsOption.Value != null)
                {
                    writer.WritePropertyName("tags");
                    JsonSerializer.Serialize(writer, reviewCaseData.Tags, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("tags");
            if (reviewCaseData.ParametersOption.IsSet)
                if (reviewCaseData.ParametersOption.Value != null)
                {
                    writer.WritePropertyName("parameters");
                    JsonSerializer.Serialize(writer, reviewCaseData.Parameters, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("parameters");
            if (reviewCaseData.CustomFieldOption.IsSet)
            {
                writer.WritePropertyName("custom_field");
                JsonSerializer.Serialize(writer, reviewCaseData.CustomField, jsonSerializerOptions);
            }
        }
    }
}
