// <auto-generated>
/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Qase.ApiClient.V1.Client;

namespace Qase.ApiClient.V1.Model
{
    /// <summary>
    /// RunQuery
    /// </summary>
    public partial class RunQuery : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunQuery" /> class.
        /// </summary>
        /// <param name="runId">runId</param>
        /// <param name="id">id</param>
        /// <param name="title">title</param>
        /// <param name="description">description</param>
        /// <param name="status">status</param>
        /// <param name="statusText">statusText</param>
        /// <param name="startTime">startTime</param>
        /// <param name="endTime">endTime</param>
        /// <param name="public">public</param>
        /// <param name="stats">stats</param>
        /// <param name="timeSpent">Time in ms.</param>
        /// <param name="elapsedTime">Time in ms.</param>
        /// <param name="varEnvironment">varEnvironment</param>
        /// <param name="milestone">milestone</param>
        /// <param name="customFields">customFields</param>
        /// <param name="tags">tags</param>
        /// <param name="cases">cases</param>
        /// <param name="planId">planId</param>
        [JsonConstructor]
        public RunQuery(long runId, Option<long?> id = default, Option<string?> title = default, Option<string?> description = default, Option<int?> status = default, Option<string?> statusText = default, Option<DateTime?> startTime = default, Option<DateTime?> endTime = default, Option<bool?> @public = default, Option<RunStats?> stats = default, Option<long?> timeSpent = default, Option<long?> elapsedTime = default, Option<RunEnvironment?> varEnvironment = default, Option<RunMilestone?> milestone = default, Option<List<CustomFieldValue>?> customFields = default, Option<List<TagValue>?> tags = default, Option<List<long>?> cases = default, Option<long?> planId = default)
        {
            RunId = runId;
            IdOption = id;
            TitleOption = title;
            DescriptionOption = description;
            StatusOption = status;
            StatusTextOption = statusText;
            StartTimeOption = startTime;
            EndTimeOption = endTime;
            PublicOption = @public;
            StatsOption = stats;
            TimeSpentOption = timeSpent;
            ElapsedTimeOption = elapsedTime;
            VarEnvironmentOption = varEnvironment;
            MilestoneOption = milestone;
            CustomFieldsOption = customFields;
            TagsOption = tags;
            CasesOption = cases;
            PlanIdOption = planId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RunId
        /// </summary>
        [JsonPropertyName("run_id")]
        public long RunId { get; set; }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long? Id { get { return this.IdOption; } set { this.IdOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public int? Status { get { return this.StatusOption; } set { this.StatusOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of StatusText
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusTextOption { get; private set; }

        /// <summary>
        /// Gets or Sets StatusText
        /// </summary>
        [JsonPropertyName("status_text")]
        public string? StatusText { get { return this.StatusTextOption; } set { this.StatusTextOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of StartTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StartTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets StartTime
        /// </summary>
        /* <example>2021-12-30T19:23:59Z</example> */
        [JsonPropertyName("start_time")]
        public DateTime? StartTime { get { return this.StartTimeOption; } set { this.StartTimeOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of EndTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> EndTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets EndTime
        /// </summary>
        /* <example>2021-12-30T19:23:59Z</example> */
        [JsonPropertyName("end_time")]
        public DateTime? EndTime { get { return this.EndTimeOption; } set { this.EndTimeOption = new Option<DateTime?>(value); } }

        /// <summary>
        /// Used to track the state of Public
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> PublicOption { get; private set; }

        /// <summary>
        /// Gets or Sets Public
        /// </summary>
        [JsonPropertyName("public")]
        public bool? Public { get { return this.PublicOption; } set { this.PublicOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of Stats
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RunStats?> StatsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Stats
        /// </summary>
        [JsonPropertyName("stats")]
        public RunStats? Stats { get { return this.StatsOption; } set { this.StatsOption = new Option<RunStats?>(value); } }

        /// <summary>
        /// Used to track the state of TimeSpent
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> TimeSpentOption { get; private set; }

        /// <summary>
        /// Time in ms.
        /// </summary>
        /// <value>Time in ms.</value>
        [JsonPropertyName("time_spent")]
        public long? TimeSpent { get { return this.TimeSpentOption; } set { this.TimeSpentOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of ElapsedTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> ElapsedTimeOption { get; private set; }

        /// <summary>
        /// Time in ms.
        /// </summary>
        /// <value>Time in ms.</value>
        [JsonPropertyName("elapsed_time")]
        public long? ElapsedTime { get { return this.ElapsedTimeOption; } set { this.ElapsedTimeOption = new Option<long?>(value); } }

        /// <summary>
        /// Used to track the state of VarEnvironment
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RunEnvironment?> VarEnvironmentOption { get; private set; }

        /// <summary>
        /// Gets or Sets VarEnvironment
        /// </summary>
        [JsonPropertyName("environment")]
        public RunEnvironment? VarEnvironment { get { return this.VarEnvironmentOption; } set { this.VarEnvironmentOption = new Option<RunEnvironment?>(value); } }

        /// <summary>
        /// Used to track the state of Milestone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RunMilestone?> MilestoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets Milestone
        /// </summary>
        [JsonPropertyName("milestone")]
        public RunMilestone? Milestone { get { return this.MilestoneOption; } set { this.MilestoneOption = new Option<RunMilestone?>(value); } }

        /// <summary>
        /// Used to track the state of CustomFields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CustomFieldValue>?> CustomFieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomFields
        /// </summary>
        [JsonPropertyName("custom_fields")]
        public List<CustomFieldValue>? CustomFields { get { return this.CustomFieldsOption; } set { this.CustomFieldsOption = new Option<List<CustomFieldValue>?>(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<TagValue>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<TagValue>? Tags { get { return this.TagsOption; } set { this.TagsOption = new Option<List<TagValue>?>(value); } }

        /// <summary>
        /// Used to track the state of Cases
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<long>?> CasesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cases
        /// </summary>
        [JsonPropertyName("cases")]
        public List<long>? Cases { get { return this.CasesOption; } set { this.CasesOption = new Option<List<long>?>(value); } }

        /// <summary>
        /// Used to track the state of PlanId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> PlanIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets PlanId
        /// </summary>
        [JsonPropertyName("plan_id")]
        public long? PlanId { get { return this.PlanIdOption; } set { this.PlanIdOption = new Option<long?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunQuery {\n");
            sb.Append("  RunId: ").Append(RunId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusText: ").Append(StatusText).Append("\n");
            sb.Append("  StartTime: ").Append(StartTime).Append("\n");
            sb.Append("  EndTime: ").Append(EndTime).Append("\n");
            sb.Append("  Public: ").Append(Public).Append("\n");
            sb.Append("  Stats: ").Append(Stats).Append("\n");
            sb.Append("  TimeSpent: ").Append(TimeSpent).Append("\n");
            sb.Append("  ElapsedTime: ").Append(ElapsedTime).Append("\n");
            sb.Append("  VarEnvironment: ").Append(VarEnvironment).Append("\n");
            sb.Append("  Milestone: ").Append(Milestone).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Cases: ").Append(Cases).Append("\n");
            sb.Append("  PlanId: ").Append(PlanId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RunQuery" />
    /// </summary>
    public class RunQueryJsonConverter : JsonConverter<RunQuery>
    {
        /// <summary>
        /// The format to use to serialize StartTime
        /// </summary>
        public static string StartTimeFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize EndTime
        /// </summary>
        public static string EndTimeFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="RunQuery" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RunQuery Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> runId = default;
            Option<long?> id = default;
            Option<string?> title = default;
            Option<string?> description = default;
            Option<int?> status = default;
            Option<string?> statusText = default;
            Option<DateTime?> startTime = default;
            Option<DateTime?> endTime = default;
            Option<bool?> varPublic = default;
            Option<RunStats?> stats = default;
            Option<long?> timeSpent = default;
            Option<long?> elapsedTime = default;
            Option<RunEnvironment?> varEnvironment = default;
            Option<RunMilestone?> milestone = default;
            Option<List<CustomFieldValue>?> customFields = default;
            Option<List<TagValue>?> tags = default;
            Option<List<long>?> cases = default;
            Option<long?> planId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "run_id":
                            runId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "id":
                            id = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "status":
                            status = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "status_text":
                            statusText = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "start_time":
                            startTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "end_time":
                            endTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "public":
                            varPublic = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "stats":
                            stats = new Option<RunStats?>(JsonSerializer.Deserialize<RunStats>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "time_spent":
                            timeSpent = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "elapsed_time":
                            elapsedTime = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "environment":
                            varEnvironment = new Option<RunEnvironment?>(JsonSerializer.Deserialize<RunEnvironment>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "milestone":
                            milestone = new Option<RunMilestone?>(JsonSerializer.Deserialize<RunMilestone>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "custom_fields":
                            customFields = new Option<List<CustomFieldValue>?>(JsonSerializer.Deserialize<List<CustomFieldValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tags":
                            tags = new Option<List<TagValue>?>(JsonSerializer.Deserialize<List<TagValue>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "cases":
                            cases = new Option<List<long>?>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "plan_id":
                            planId = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!runId.IsSet)
                throw new ArgumentException("Property is required for class RunQuery.", nameof(runId));

            if (runId.IsSet && runId.Value == null)
                throw new ArgumentNullException(nameof(runId), "Property is not nullable for class RunQuery.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class RunQuery.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class RunQuery.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class RunQuery.");

            if (statusText.IsSet && statusText.Value == null)
                throw new ArgumentNullException(nameof(statusText), "Property is not nullable for class RunQuery.");

            if (varPublic.IsSet && varPublic.Value == null)
                throw new ArgumentNullException(nameof(varPublic), "Property is not nullable for class RunQuery.");

            if (stats.IsSet && stats.Value == null)
                throw new ArgumentNullException(nameof(stats), "Property is not nullable for class RunQuery.");

            if (timeSpent.IsSet && timeSpent.Value == null)
                throw new ArgumentNullException(nameof(timeSpent), "Property is not nullable for class RunQuery.");

            if (elapsedTime.IsSet && elapsedTime.Value == null)
                throw new ArgumentNullException(nameof(elapsedTime), "Property is not nullable for class RunQuery.");

            if (customFields.IsSet && customFields.Value == null)
                throw new ArgumentNullException(nameof(customFields), "Property is not nullable for class RunQuery.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class RunQuery.");

            if (cases.IsSet && cases.Value == null)
                throw new ArgumentNullException(nameof(cases), "Property is not nullable for class RunQuery.");

            return new RunQuery(runId.Value!.Value!, id, title, description, status, statusText, startTime, endTime, varPublic, stats, timeSpent, elapsedTime, varEnvironment, milestone, customFields, tags, cases, planId);
        }

        /// <summary>
        /// Serializes a <see cref="RunQuery" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="runQuery"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RunQuery runQuery, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, runQuery, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RunQuery" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="runQuery"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RunQuery runQuery, JsonSerializerOptions jsonSerializerOptions)
        {
            if (runQuery.TitleOption.IsSet && runQuery.Title == null)
                throw new ArgumentNullException(nameof(runQuery.Title), "Property is required for class RunQuery.");

            if (runQuery.StatusTextOption.IsSet && runQuery.StatusText == null)
                throw new ArgumentNullException(nameof(runQuery.StatusText), "Property is required for class RunQuery.");

            if (runQuery.StatsOption.IsSet && runQuery.Stats == null)
                throw new ArgumentNullException(nameof(runQuery.Stats), "Property is required for class RunQuery.");

            if (runQuery.CustomFieldsOption.IsSet && runQuery.CustomFields == null)
                throw new ArgumentNullException(nameof(runQuery.CustomFields), "Property is required for class RunQuery.");

            if (runQuery.TagsOption.IsSet && runQuery.Tags == null)
                throw new ArgumentNullException(nameof(runQuery.Tags), "Property is required for class RunQuery.");

            if (runQuery.CasesOption.IsSet && runQuery.Cases == null)
                throw new ArgumentNullException(nameof(runQuery.Cases), "Property is required for class RunQuery.");

            writer.WriteNumber("run_id", runQuery.RunId);

            if (runQuery.IdOption.IsSet)
                writer.WriteNumber("id", runQuery.IdOption.Value!.Value);

            if (runQuery.TitleOption.IsSet)
                writer.WriteString("title", runQuery.Title);

            if (runQuery.DescriptionOption.IsSet)
                if (runQuery.DescriptionOption.Value != null)
                    writer.WriteString("description", runQuery.Description);
                else
                    writer.WriteNull("description");

            if (runQuery.StatusOption.IsSet)
                writer.WriteNumber("status", runQuery.StatusOption.Value!.Value);

            if (runQuery.StatusTextOption.IsSet)
                writer.WriteString("status_text", runQuery.StatusText);

            if (runQuery.StartTimeOption.IsSet)
                if (runQuery.StartTimeOption.Value != null)
                    writer.WriteString("start_time", runQuery.StartTimeOption.Value!.Value.ToString(StartTimeFormat));
                else
                    writer.WriteNull("start_time");

            if (runQuery.EndTimeOption.IsSet)
                if (runQuery.EndTimeOption.Value != null)
                    writer.WriteString("end_time", runQuery.EndTimeOption.Value!.Value.ToString(EndTimeFormat));
                else
                    writer.WriteNull("end_time");

            if (runQuery.PublicOption.IsSet)
                writer.WriteBoolean("public", runQuery.PublicOption.Value!.Value);

            if (runQuery.StatsOption.IsSet)
            {
                writer.WritePropertyName("stats");
                JsonSerializer.Serialize(writer, runQuery.Stats, jsonSerializerOptions);
            }
            if (runQuery.TimeSpentOption.IsSet)
                writer.WriteNumber("time_spent", runQuery.TimeSpentOption.Value!.Value);

            if (runQuery.ElapsedTimeOption.IsSet)
                writer.WriteNumber("elapsed_time", runQuery.ElapsedTimeOption.Value!.Value);

            if (runQuery.VarEnvironmentOption.IsSet)
                if (runQuery.VarEnvironmentOption.Value != null)
                {
                    writer.WritePropertyName("environment");
                    JsonSerializer.Serialize(writer, runQuery.VarEnvironment, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("environment");
            if (runQuery.MilestoneOption.IsSet)
                if (runQuery.MilestoneOption.Value != null)
                {
                    writer.WritePropertyName("milestone");
                    JsonSerializer.Serialize(writer, runQuery.Milestone, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("milestone");
            if (runQuery.CustomFieldsOption.IsSet)
            {
                writer.WritePropertyName("custom_fields");
                JsonSerializer.Serialize(writer, runQuery.CustomFields, jsonSerializerOptions);
            }
            if (runQuery.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, runQuery.Tags, jsonSerializerOptions);
            }
            if (runQuery.CasesOption.IsSet)
            {
                writer.WritePropertyName("cases");
                JsonSerializer.Serialize(writer, runQuery.Cases, jsonSerializerOptions);
            }
            if (runQuery.PlanIdOption.IsSet)
                if (runQuery.PlanIdOption.Value != null)
                    writer.WriteNumber("plan_id", runQuery.PlanIdOption.Value!.Value);
                else
                    writer.WriteNull("plan_id");
        }
    }
}
