// <auto-generated>
/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Qase.ApiClient.V1.Client;

namespace Qase.ApiClient.V1.Model
{
    /// <summary>
    /// SearchResponseAllOfResult
    /// </summary>
    public partial class SearchResponseAllOfResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchResponseAllOfResult" /> class.
        /// </summary>
        /// <param name="entities">entities</param>
        /// <param name="total">total</param>
        [JsonConstructor]
        public SearchResponseAllOfResult(List<SearchResponseAllOfResultEntities> entities, int total)
        {
            Entities = entities;
            Total = total;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Entities
        /// </summary>
        [JsonPropertyName("entities")]
        public List<SearchResponseAllOfResultEntities> Entities { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public int Total { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchResponseAllOfResult {\n");
            sb.Append("  Entities: ").Append(Entities).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchResponseAllOfResult" />
    /// </summary>
    public class SearchResponseAllOfResultJsonConverter : JsonConverter<SearchResponseAllOfResult>
    {
        /// <summary>
        /// Deserializes json to <see cref="SearchResponseAllOfResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SearchResponseAllOfResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<SearchResponseAllOfResultEntities>?> entities = default;
            Option<int?> total = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "entities":
                            entities = new Option<List<SearchResponseAllOfResultEntities>?>(JsonSerializer.Deserialize<List<SearchResponseAllOfResultEntities>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "total":
                            total = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!entities.IsSet)
                throw new ArgumentException("Property is required for class SearchResponseAllOfResult.", nameof(entities));

            if (!total.IsSet)
                throw new ArgumentException("Property is required for class SearchResponseAllOfResult.", nameof(total));

            if (entities.IsSet && entities.Value == null)
                throw new ArgumentNullException(nameof(entities), "Property is not nullable for class SearchResponseAllOfResult.");

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class SearchResponseAllOfResult.");

            return new SearchResponseAllOfResult(entities.Value!, total.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SearchResponseAllOfResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchResponseAllOfResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SearchResponseAllOfResult searchResponseAllOfResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, searchResponseAllOfResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SearchResponseAllOfResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchResponseAllOfResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SearchResponseAllOfResult searchResponseAllOfResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (searchResponseAllOfResult.Entities == null)
                throw new ArgumentNullException(nameof(searchResponseAllOfResult.Entities), "Property is required for class SearchResponseAllOfResult.");

            writer.WritePropertyName("entities");
            JsonSerializer.Serialize(writer, searchResponseAllOfResult.Entities, jsonSerializerOptions);
            writer.WriteNumber("total", searchResponseAllOfResult.Total);
        }
    }
}
