// <auto-generated>
/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Qase.ApiClient.V1.Client;

namespace Qase.ApiClient.V1.Model
{
    /// <summary>
    /// SharedParameterCreate
    /// </summary>
    public partial class SharedParameterCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SharedParameterCreate" /> class.
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="type">type</param>
        /// <param name="isEnabledForAllProjects">isEnabledForAllProjects</param>
        /// <param name="parameters">parameters</param>
        /// <param name="projectCodes">List of project codes to associate with this shared parameter</param>
        [JsonConstructor]
        public SharedParameterCreate(string title, TypeEnum type, bool isEnabledForAllProjects, SharedParameterParameter parameters, Option<List<string>?> projectCodes = default)
        {
            Title = title;
            Type = type;
            IsEnabledForAllProjects = isEnabledForAllProjects;
            Parameters = parameters;
            ProjectCodesOption = projectCodes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Single for value: single
            /// </summary>
            Single = 1,

            /// <summary>
            /// Enum Group for value: group
            /// </summary>
            Group = 2
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("single"))
                return TypeEnum.Single;

            if (value.Equals("group"))
                return TypeEnum.Group;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("single"))
                return TypeEnum.Single;

            if (value.Equals("group"))
                return TypeEnum.Group;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.Single)
                return "single";

            if (value == TypeEnum.Group)
                return "group";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets IsEnabledForAllProjects
        /// </summary>
        [JsonPropertyName("is_enabled_for_all_projects")]
        public bool IsEnabledForAllProjects { get; set; }

        /// <summary>
        /// Gets or Sets Parameters
        /// </summary>
        [JsonPropertyName("parameters")]
        public SharedParameterParameter Parameters { get; set; }

        /// <summary>
        /// Used to track the state of ProjectCodes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ProjectCodesOption { get; private set; }

        /// <summary>
        /// List of project codes to associate with this shared parameter
        /// </summary>
        /// <value>List of project codes to associate with this shared parameter</value>
        [JsonPropertyName("project_codes")]
        public List<string>? ProjectCodes { get { return this.ProjectCodesOption; } set { this.ProjectCodesOption = new Option<List<string>?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SharedParameterCreate {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  IsEnabledForAllProjects: ").Append(IsEnabledForAllProjects).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  ProjectCodes: ").Append(ProjectCodes).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Title, length must be less than 255.", new [] { "Title" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SharedParameterCreate" />
    /// </summary>
    public class SharedParameterCreateJsonConverter : JsonConverter<SharedParameterCreate>
    {
        /// <summary>
        /// Deserializes json to <see cref="SharedParameterCreate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SharedParameterCreate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<SharedParameterCreate.TypeEnum?> type = default;
            Option<bool?> isEnabledForAllProjects = default;
            Option<SharedParameterParameter?> parameters = default;
            Option<List<string>?> projectCodes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<SharedParameterCreate.TypeEnum?>(SharedParameterCreate.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "is_enabled_for_all_projects":
                            isEnabledForAllProjects = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "parameters":
                            parameters = new Option<SharedParameterParameter?>(JsonSerializer.Deserialize<SharedParameterParameter>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "project_codes":
                            projectCodes = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class SharedParameterCreate.", nameof(title));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class SharedParameterCreate.", nameof(type));

            if (!isEnabledForAllProjects.IsSet)
                throw new ArgumentException("Property is required for class SharedParameterCreate.", nameof(isEnabledForAllProjects));

            if (!parameters.IsSet)
                throw new ArgumentException("Property is required for class SharedParameterCreate.", nameof(parameters));

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class SharedParameterCreate.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class SharedParameterCreate.");

            if (isEnabledForAllProjects.IsSet && isEnabledForAllProjects.Value == null)
                throw new ArgumentNullException(nameof(isEnabledForAllProjects), "Property is not nullable for class SharedParameterCreate.");

            if (parameters.IsSet && parameters.Value == null)
                throw new ArgumentNullException(nameof(parameters), "Property is not nullable for class SharedParameterCreate.");

            if (projectCodes.IsSet && projectCodes.Value == null)
                throw new ArgumentNullException(nameof(projectCodes), "Property is not nullable for class SharedParameterCreate.");

            return new SharedParameterCreate(title.Value!, type.Value!.Value!, isEnabledForAllProjects.Value!.Value!, parameters.Value!, projectCodes);
        }

        /// <summary>
        /// Serializes a <see cref="SharedParameterCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sharedParameterCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SharedParameterCreate sharedParameterCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sharedParameterCreate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SharedParameterCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sharedParameterCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SharedParameterCreate sharedParameterCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sharedParameterCreate.Title == null)
                throw new ArgumentNullException(nameof(sharedParameterCreate.Title), "Property is required for class SharedParameterCreate.");

            if (sharedParameterCreate.Parameters == null)
                throw new ArgumentNullException(nameof(sharedParameterCreate.Parameters), "Property is required for class SharedParameterCreate.");

            if (sharedParameterCreate.ProjectCodesOption.IsSet && sharedParameterCreate.ProjectCodes == null)
                throw new ArgumentNullException(nameof(sharedParameterCreate.ProjectCodes), "Property is required for class SharedParameterCreate.");

            writer.WriteString("title", sharedParameterCreate.Title);

            var typeRawValue = SharedParameterCreate.TypeEnumToJsonValue(sharedParameterCreate.Type);
            writer.WriteString("type", typeRawValue);
            writer.WriteBoolean("is_enabled_for_all_projects", sharedParameterCreate.IsEnabledForAllProjects);

            writer.WritePropertyName("parameters");
            JsonSerializer.Serialize(writer, sharedParameterCreate.Parameters, jsonSerializerOptions);
            if (sharedParameterCreate.ProjectCodesOption.IsSet)
            {
                writer.WritePropertyName("project_codes");
                JsonSerializer.Serialize(writer, sharedParameterCreate.ProjectCodes, jsonSerializerOptions);
            }
        }
    }
}
