// <auto-generated>
/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Qase.ApiClient.V1.Client;

namespace Qase.ApiClient.V1.Model
{
    /// <summary>
    /// SharedStepContentCreate
    /// </summary>
    public partial class SharedStepContentCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SharedStepContentCreate" /> class.
        /// </summary>
        /// <param name="action">action</param>
        /// <param name="hash">hash</param>
        /// <param name="expectedResult">expectedResult</param>
        /// <param name="data">data</param>
        /// <param name="attachments">A list of Attachment hashes.</param>
        [JsonConstructor]
        public SharedStepContentCreate(string action, Option<string?> hash = default, Option<string?> expectedResult = default, Option<string?> data = default, Option<List<string>?> attachments = default)
        {
            Action = action;
            HashOption = hash;
            ExpectedResultOption = expectedResult;
            DataOption = data;
            AttachmentsOption = attachments;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [JsonPropertyName("action")]
        public string Action { get; set; }

        /// <summary>
        /// Used to track the state of Hash
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HashOption { get; private set; }

        /// <summary>
        /// Gets or Sets Hash
        /// </summary>
        [JsonPropertyName("hash")]
        public string? Hash { get { return this.HashOption; } set { this.HashOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of ExpectedResult
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExpectedResultOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpectedResult
        /// </summary>
        [JsonPropertyName("expected_result")]
        public string? ExpectedResult { get { return this.ExpectedResultOption; } set { this.ExpectedResultOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public string? Data { get { return this.DataOption; } set { this.DataOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Attachments
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> AttachmentsOption { get; private set; }

        /// <summary>
        /// A list of Attachment hashes.
        /// </summary>
        /// <value>A list of Attachment hashes.</value>
        [JsonPropertyName("attachments")]
        public List<string>? Attachments { get { return this.AttachmentsOption; } set { this.AttachmentsOption = new Option<List<string>?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SharedStepContentCreate {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Hash: ").Append(Hash).Append("\n");
            sb.Append("  ExpectedResult: ").Append(ExpectedResult).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SharedStepContentCreate" />
    /// </summary>
    public class SharedStepContentCreateJsonConverter : JsonConverter<SharedStepContentCreate>
    {
        /// <summary>
        /// Deserializes json to <see cref="SharedStepContentCreate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SharedStepContentCreate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> action = default;
            Option<string?> hash = default;
            Option<string?> expectedResult = default;
            Option<string?> data = default;
            Option<List<string>?> attachments = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "action":
                            action = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "hash":
                            hash = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expected_result":
                            expectedResult = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "data":
                            data = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "attachments":
                            attachments = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!action.IsSet)
                throw new ArgumentException("Property is required for class SharedStepContentCreate.", nameof(action));

            if (action.IsSet && action.Value == null)
                throw new ArgumentNullException(nameof(action), "Property is not nullable for class SharedStepContentCreate.");

            if (hash.IsSet && hash.Value == null)
                throw new ArgumentNullException(nameof(hash), "Property is not nullable for class SharedStepContentCreate.");

            if (expectedResult.IsSet && expectedResult.Value == null)
                throw new ArgumentNullException(nameof(expectedResult), "Property is not nullable for class SharedStepContentCreate.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class SharedStepContentCreate.");

            if (attachments.IsSet && attachments.Value == null)
                throw new ArgumentNullException(nameof(attachments), "Property is not nullable for class SharedStepContentCreate.");

            return new SharedStepContentCreate(action.Value!, hash, expectedResult, data, attachments);
        }

        /// <summary>
        /// Serializes a <see cref="SharedStepContentCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sharedStepContentCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SharedStepContentCreate sharedStepContentCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sharedStepContentCreate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SharedStepContentCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sharedStepContentCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SharedStepContentCreate sharedStepContentCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sharedStepContentCreate.Action == null)
                throw new ArgumentNullException(nameof(sharedStepContentCreate.Action), "Property is required for class SharedStepContentCreate.");

            if (sharedStepContentCreate.HashOption.IsSet && sharedStepContentCreate.Hash == null)
                throw new ArgumentNullException(nameof(sharedStepContentCreate.Hash), "Property is required for class SharedStepContentCreate.");

            if (sharedStepContentCreate.ExpectedResultOption.IsSet && sharedStepContentCreate.ExpectedResult == null)
                throw new ArgumentNullException(nameof(sharedStepContentCreate.ExpectedResult), "Property is required for class SharedStepContentCreate.");

            if (sharedStepContentCreate.DataOption.IsSet && sharedStepContentCreate.Data == null)
                throw new ArgumentNullException(nameof(sharedStepContentCreate.Data), "Property is required for class SharedStepContentCreate.");

            if (sharedStepContentCreate.AttachmentsOption.IsSet && sharedStepContentCreate.Attachments == null)
                throw new ArgumentNullException(nameof(sharedStepContentCreate.Attachments), "Property is required for class SharedStepContentCreate.");

            writer.WriteString("action", sharedStepContentCreate.Action);

            if (sharedStepContentCreate.HashOption.IsSet)
                writer.WriteString("hash", sharedStepContentCreate.Hash);

            if (sharedStepContentCreate.ExpectedResultOption.IsSet)
                writer.WriteString("expected_result", sharedStepContentCreate.ExpectedResult);

            if (sharedStepContentCreate.DataOption.IsSet)
                writer.WriteString("data", sharedStepContentCreate.Data);

            if (sharedStepContentCreate.AttachmentsOption.IsSet)
            {
                writer.WritePropertyName("attachments");
                JsonSerializer.Serialize(writer, sharedStepContentCreate.Attachments, jsonSerializerOptions);
            }
        }
    }
}
