// <auto-generated>
/*
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Qase.ApiClient.V1.Client;

namespace Qase.ApiClient.V1.Model
{
    /// <summary>
    /// UserListResponseAllOfResult
    /// </summary>
    public partial class UserListResponseAllOfResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserListResponseAllOfResult" /> class.
        /// </summary>
        /// <param name="total">total</param>
        /// <param name="filtered">filtered</param>
        /// <param name="count">count</param>
        /// <param name="entities">entities</param>
        [JsonConstructor]
        public UserListResponseAllOfResult(Option<int?> total = default, Option<int?> filtered = default, Option<int?> count = default, Option<List<User>?> entities = default)
        {
            TotalOption = total;
            FilteredOption = filtered;
            CountOption = count;
            EntitiesOption = entities;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Total
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalOption { get; private set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public int? Total { get { return this.TotalOption; } set { this.TotalOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Filtered
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FilteredOption { get; private set; }

        /// <summary>
        /// Gets or Sets Filtered
        /// </summary>
        [JsonPropertyName("filtered")]
        public int? Filtered { get { return this.FilteredOption; } set { this.FilteredOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Count
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [JsonPropertyName("count")]
        public int? Count { get { return this.CountOption; } set { this.CountOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of Entities
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<User>?> EntitiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Entities
        /// </summary>
        [JsonPropertyName("entities")]
        public List<User>? Entities { get { return this.EntitiesOption; } set { this.EntitiesOption = new Option<List<User>?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserListResponseAllOfResult {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Filtered: ").Append(Filtered).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Entities: ").Append(Entities).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserListResponseAllOfResult" />
    /// </summary>
    public class UserListResponseAllOfResultJsonConverter : JsonConverter<UserListResponseAllOfResult>
    {
        /// <summary>
        /// Deserializes json to <see cref="UserListResponseAllOfResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserListResponseAllOfResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> total = default;
            Option<int?> filtered = default;
            Option<int?> count = default;
            Option<List<User>?> entities = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "total":
                            total = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "filtered":
                            filtered = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "count":
                            count = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "entities":
                            entities = new Option<List<User>?>(JsonSerializer.Deserialize<List<User>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class UserListResponseAllOfResult.");

            if (filtered.IsSet && filtered.Value == null)
                throw new ArgumentNullException(nameof(filtered), "Property is not nullable for class UserListResponseAllOfResult.");

            if (count.IsSet && count.Value == null)
                throw new ArgumentNullException(nameof(count), "Property is not nullable for class UserListResponseAllOfResult.");

            if (entities.IsSet && entities.Value == null)
                throw new ArgumentNullException(nameof(entities), "Property is not nullable for class UserListResponseAllOfResult.");

            return new UserListResponseAllOfResult(total, filtered, count, entities);
        }

        /// <summary>
        /// Serializes a <see cref="UserListResponseAllOfResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userListResponseAllOfResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserListResponseAllOfResult userListResponseAllOfResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userListResponseAllOfResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserListResponseAllOfResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userListResponseAllOfResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserListResponseAllOfResult userListResponseAllOfResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (userListResponseAllOfResult.EntitiesOption.IsSet && userListResponseAllOfResult.Entities == null)
                throw new ArgumentNullException(nameof(userListResponseAllOfResult.Entities), "Property is required for class UserListResponseAllOfResult.");

            if (userListResponseAllOfResult.TotalOption.IsSet)
                writer.WriteNumber("total", userListResponseAllOfResult.TotalOption.Value!.Value);

            if (userListResponseAllOfResult.FilteredOption.IsSet)
                writer.WriteNumber("filtered", userListResponseAllOfResult.FilteredOption.Value!.Value);

            if (userListResponseAllOfResult.CountOption.IsSet)
                writer.WriteNumber("count", userListResponseAllOfResult.CountOption.Value!.Value);

            if (userListResponseAllOfResult.EntitiesOption.IsSet)
            {
                writer.WritePropertyName("entities");
                JsonSerializer.Serialize(writer, userListResponseAllOfResult.Entities, jsonSerializerOptions);
            }
        }
    }
}
